# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.txtBr_rsv_messaqe = QtWidgets.QTextBrowser(Form)
        self.txtBr_rsv_messaqe.setGeometry(QtCore.QRect(10, 10, 371, 192))
        self.txtBr_rsv_messaqe.setObjectName("txtBr_rsv_messaqe")
        self.txtEd_send_msg = QtWidgets.QTextEdit(Form)
        self.txtEd_send_msg.setGeometry(QtCore.QRect(10, 210, 371, 31))
        self.txtEd_send_msg.setObjectName("txtEd_send_msg")
        self.btn_send_msg = QtWidgets.QPushButton(Form)
        self.btn_send_msg.setGeometry(QtCore.QRect(90, 250, 75, 23))
        self.btn_send_msg.setObjectName("btn_send_msg")
        self.btn_quit = QtWidgets.QPushButton(Form)
        self.btn_quit.setGeometry(QtCore.QRect(230, 250, 75, 23))
        self.btn_quit.setObjectName("btn_quit")

        self.retranslateUi(Form)
        self.btn_quit.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_send_msg.setText(_translate("Form", "发送"))
        self.btn_quit.setText(_translate("Form", "退出"))

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    widget = Ui_Form()
    widget.show()
    sys.exit(app.exec_())
